### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by call-a3** [adana-coverage/babel-plugin-transform-adana#4]
```
\D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\transformation\file\index.js:520
      throw err;
      ^

TypeError: D:/Users/Adriaan/Workspace/Skedify/skedify-plugin/tests/test_helper.js: Cannot read property 'start' of undefined
    at PluginPass.visitConditional (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-plugin-transform-adana\dist\instrumenter.js:327:39)
    at D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\visitors.js:271:19
    at NodePath._call (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\index.js:139:17)
    at Object.traverse [as default] (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-traverse\lib\index.js:61:12)
    at File.transform (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\transformation\file\index.js:475:31)
    at D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\transformation\pipeline.js:46:19
    at File.wrap (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\transformation\file\index.js:488:16)
    at Pipeline.transform (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\transformation\pipeline.js:43:17)
    at Object.transformFileSync (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\api\node.js:113:10)
    at compile (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\api\register\node.js:111:20)
    at loader (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\api\register\node.js:136:14)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\babel-core\lib\api\register\node.js:146:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\mocha\bin\_mocha:304:3
    at Array.forEach (native)
    at Object.<anonymous> (D:\Users\Adriaan\Workspace\Skedify\skedify-plugin\node_modules\mocha\bin\_mocha:303:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Adriaan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test" "--" "--watch"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! skedify-plugin@0.0.1-draft.2 test: `mocha --compilers js:babel-core/register --require ./tests/test_helper.js "tests/**/*.js" "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skedify-plugin@0.0.1-draft.2 test script 'mocha --compilers js:babel-core/register --require ./tests/test_helper.js "tests/**/*.js" "--watch"'.
```

**Comment by call-a3** [comment]
Sorry I don't give more information. I have no idea what could be the cause of this error, so I have no idea what extra info might be relevant to the resolution. If I can provide any more helpful information, please let me know!

**Comment by izaakschroeder** [comment]
Sorry for the delay @call-a3 it's been a busy month; finally get back around to this. Just fixed a whole bunch of stuff the past week or two, but it's not totally ironed out yet. Feel free to poke around if you want, but I should have something more substantive in the next little while. :smile: 

Thanks for the interest!

**Comment by izaakschroeder** [comment]
Alright well I think the dust has settled now for the most part. See `README.md` for updated instructions. `adana` is now being used successfully on a couple projects :smile: If there are still issues, let me know!
